namespace GodotCoop
{
    /// <summary>
    /// Input map generated by the excellent third-party GodotSharp generators.
    /// Allows us to access our input constants in a type-safe way.
    /// </summary>
    public static class GameInputs
    {
        // Define input actions as constants
        public const string MoveUp = "move_up";
        public const string MoveDown = "move_down";
        public const string MoveLeft = "move_left";
        public const string MoveRight = "move_right";
        public const string Jump = "jump";
    }
}
